# Generated by Django 5.2.11 on 2026-02-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deployment_mode',
            field=models.CharField(choices=[('vscode', 'VS Code'), ('azure_app_service', 'Azure App Service')], default='vscode', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deployment_mode_prompt_seen',
            field=models.BooleanField(default=False),
        ),
    ]
